#!/usr/bin/env python
"""Write model/verification_model.toml from model/parameter_weights.toml and the 10.56 km input raster.

    python scripts/make_parameters.py --input data/br_10km.tif

The potentials are  const + sum(beta * x) + rho * lag,  with beta = w / sigma and const chosen so that the mean
potential of every class is zero at the start (docs/PARAMETERIZATION.md). The statistics are taken once from the
10.56 km input raster and applied unchanged to every other resolution, so that the model is the same on every grid.
Also writes model/parameters_derivation.json (statistics, constants, hash of the input raster, hash of the weights).
"""
from __future__ import annotations

import argparse
import pathlib

import numpy as np

try:
    from _common import LAND_USES, MODEL_TOML, ROOT, load_toml, read_bands, sha256_file, write_json
except ImportError:  # pragma: no cover
    from scripts._common import LAND_USES, MODEL_TOML, ROOT, load_toml, read_bands, sha256_file, write_json

WEIGHTS = ROOT / "model" / "parameter_weights.toml"
DERIVATION = ROOT / "model" / "parameters_derivation.json"
NATURAL = ("forest_vegetation", "country_vegetation")
MOVING = [lu for lu in LAND_USES if lu != "others"]

HEADER = """\
# Verification model: the structure of LuccME-BR (continuous allocation with saturation, spatial-lag potential)
# with DECLARED, illustrative parameters. Generated by scripts/make_parameters.py from model/parameter_weights.toml
# and the statistics of the 10.56 km input raster (model/parameters_derivation.json); do not edit by hand.
# It is not LuccME-BR and its outputs are not land-use projections. How the values were reached, and what was tried
# before (the published S2 parameters, kept in model/reference/), is in docs/PARAMETERIZATION.md.
#
# Units of the input raster: land uses are shares (0-1); c_ucspas is a protected share; c_nusett is a count; e_* are
# distances (m) or cost units.
#
# Run by:  python scripts/run_experiment.py --input <input.tif> --label <label>

[model]
executor_module  = "disslucc.executors"
name             = "lucc_continuous_saturation"
class            = "lucc_continuous_saturation"
description      = "Verification model on the Brazil input raster (declared parameters)"
package          = "disslucc==0.5.0"
dissmodel        = ">=0.6.4,<0.7.0"

land_use_types = ["forest_vegetation", "country_vegetation", "pasture_management",
                  "agricultural", "mosaic_of_occupations", "forestry", "others"]
land_use_no_data     = "others"
complementar_lu      = "forest_vegetation"
attr_protection      = "c_ucspas"
saturation_indicator = "saturation"
max_iteration        = {max_iteration}
# cell_area, max_difference and n_steps come from the scenario and the grid (scripts/run_experiment.py)
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", required=True, type=pathlib.Path)
    ap.add_argument("--weights", type=pathlib.Path, default=WEIGHTS)
    ap.add_argument("--out", type=pathlib.Path, default=MODEL_TOML)
    a = ap.parse_args()

    w = load_toml(a.weights)
    rho = float(w["rho"]["value"])
    al = w["allocation"]
    arr, _, _ = read_bands(a.input)  # dict-like: band name -> 2D array (see _common.read_bands)
    mask = arr["mask"] > 0

    def stat(name):
        x = arr[name][mask].astype("float64")
        return float(x.mean()), float(x.std())

    lines = [HEADER.format(max_iteration=int(al["max_iteration"]))]
    deriv = {"input_raster": str(a.input.name), "input_raster_sha256": sha256_file(a.input),
             "weights_sha256": sha256_file(a.weights), "rho": rho, "classes": {}}
    for lu in MOVING:
        ws = w["weights"][lu]
        mean_k, _ = stat(lu)
        betas, shift = {}, 0.0
        for d, wt in ws.items():
            mu, sd = stat(d)
            betas[d] = wt / sd
            shift += wt * mu / sd
        const = (1.0 - rho) * mean_k - shift
        deriv["classes"][lu] = {"mean_share": mean_k, "const": const,
                                "drivers": {d: {"weight": ws[d], "mean": stat(d)[0], "std": stat(d)[1], "beta": betas[d]} for d in ws}}
        lines.append(f'[[model.potential_data]]\nlu    = "{lu}"\nconst = {const:.8g}\nro    = {rho}\n  [model.potential_data.betas]')
        lines += [f"  {d} = {b:.8g}" for d, b in betas.items()]
        lines.append("")
    lines.append('[[model.potential_data]]\nlu    = "others"\nconst = 0.0\nro    = 0.0\n')
    for lu in MOVING:
        nat = lu in NATURAL
        lines.append(
            f'[[model.allocation_data]]\nlu = "{lu}"\nstatic = {w.get("static_by_class", {}).get(lu, al["static"])}\nmin_value = 0.0\nmax_value = 1.0\n'
            f'min_change = {al["min_change"]}\nmax_change = {al["max_change"]}\n'
            f'change_limiar_value = {al["natural_limiar"] if nat else al["anthropic_limiar"]}\n'
            f'max_change_above_limiar = {al["natural_above"] if nat else al["anthropic_above"]}\n')
    lines.append('[[model.allocation_data]]\nlu = "others"\nstatic = 1\nmin_value = 0.0\nmax_value = 1.0\nmin_change = 0.0\n'
                 'max_change = 1.0\nchange_limiar_value = 1.0\nmax_change_above_limiar = 0.0\n')
    a.out.write_text("\n".join(lines), encoding="utf-8")
    write_json(DERIVATION, deriv)
    print(f"wrote {a.out} and {DERIVATION}")
    for lu, c in deriv["classes"].items():
        print(f"  {lu:24s} mean share {c['mean_share']:.4f}  const {c['const']:+.5f}")


if __name__ == "__main__":
    main()
